/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IEVMVaultFactory {
  export type CreateNewVaultParamsStruct = {
    name: string;
    symbol: string;
    underlying: AddressLike;
    authority: AddressLike;
    initDepositAmount: BigNumberish;
    minDepositAmount: BigNumberish;
    maxDepositAmount: BigNumberish;
    deadline: BigNumberish;
  };

  export type CreateNewVaultParamsStructOutput = [
    name: string,
    symbol: string,
    underlying: string,
    authority: string,
    initDepositAmount: bigint,
    minDepositAmount: bigint,
    maxDepositAmount: bigint,
    deadline: bigint
  ] & {
    name: string;
    symbol: string;
    underlying: string;
    authority: string;
    initDepositAmount: bigint;
    minDepositAmount: bigint;
    maxDepositAmount: bigint;
    deadline: bigint;
  };
}

export interface IEVMVaultFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createNewVault" | "signer"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createNewVault",
    values: [IEVMVaultFactory.CreateNewVaultParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "signer", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createNewVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signer", data: BytesLike): Result;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    authority: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [vault: string, authority: string, shares: bigint];
  export interface OutputObject {
    vault: string;
    authority: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEVMVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IEVMVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: IEVMVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createNewVault: TypedContractMethod<
    [params: IEVMVaultFactory.CreateNewVaultParamsStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createNewVault"
  ): TypedContractMethod<
    [params: IEVMVaultFactory.CreateNewVaultParamsStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "VaultCreated(address,address,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
